### ISSUE TITLE
Is there any way to specify which artifact to deploy?

### ISSUE THREAD

**Issue by astj** [aereal/capistrano-strategy-jenkins_artifact#2]
Currently, this strategy deploys "first" artifact of last successful build.
- [Fetch artifact by `JenkinsApiClient.Client.Job.find_artifact`](https://github.com/aereal/capistrano-strategy-jenkins_artifact/blob/master/lib/capistrano/strategy/jenkins_artifact.rb#L21)
- [`JenkinsApiClient.Client.Job.find_artifact` returns first artifact, even if the build has multiple artifacts](https://github.com/arangamani/jenkins_api_client/blob/master/lib/jenkins_api_client/job.rb#L1554) 

I'd like to specify the artifact by its name, because my Jenkins build project produces multiple artifacts.
I know this is depending on `JenkinsApiClient`'s behavior, is there any idea?

**Comment by aereal** [comment]
@astj 
- Fetch artifact by the function `Array[Artifact] => Maybe[Artifact]` instead of `JenkinsApiClient::Client::Job#find_artifact`
  - it will be given by the configuration such as `artifact_fetch_policy`)
  - `JenkinsApiClient::Client::Job#find_artifact` (or behaves like) as default

**Comment by astj** [comment]
#4
